# -*- coding: utf-8 -*-
"""00_tensorFlow_Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-_t_wYaZbiNucpnwwoa_2SvauodYO1G
"""

# In this notebook we're going to learn some of the basic fundamental concepts of tensors using the TensorFlow
#

"""**Specifically:**

1. Introduction to tensors
2. Getting the informations from the tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function (A way to speed up your regular Python functions)
6. Using the GPUs with TensorFlow(or TPUs)
7. Exercises to try for yourself
"""

print("Hello world!")